### ISSUE TITLE
Create custom VPS via API

### ISSUE THREAD

**Issue by metti-himself** [laravel/forge-sdk#100]
Hello,

I used laravel/forge-sdk 3.3, for this pretty simple creation script:

$forge = new Laravel\Forge\Forge($API_TOKEN);

$server = $forge->createServer([
        "provider"=> "custom",
        "name"=> "xxx",
        "ip_address"=> "x.x.x.x",
        "private_ip_address"=> "x.x.x.x",
        "php_version"=> "php74"
]);
?>

As Response I simply get this:

PHP Fatal error:  Uncaught Laravel\Forge\Exceptions\ValidationException: The given data failed to pass validation. in /home/technik/forge-api/vendor/laravel/forge-sdk/src/MakesHttpRequests.php:98
Stack trace:
#0 /home/technik/forge-api/vendor/laravel/forge-sdk/src/MakesHttpRequests.php(76): Laravel\Forge\Forge->handleRequestError()
#1 /home/technik/forge-api/vendor/laravel/forge-sdk/src/MakesHttpRequests.php(34): Laravel\Forge\Forge->request()
#2 /home/technik/forge-api/vendor/laravel/forge-sdk/src/Actions/ManagesServers.php(44): Laravel\Forge\Forge->post()
#3 /home/technik/forge-api/create-server.php(10): Laravel\Forge\Forge->createServer()
#4 {main}
  thrown in /home/technik/forge-api/vendor/laravel/forge-sdk/src/MakesHttpRequests.php on line 98

Actually I wanted to create type node_balancer, but I have no clue which fields are required and which are optional. I have only two types of devices, load balancers or web servers. Can someone give me an hint in the right direction?

Best Regards 

Matthias

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
