### ISSUE TITLE
Cant set notifications for site deployments

### ISSUE THREAD

**Issue by stubbo** [laravel/forge-sdk#103]
- Forge SDK Version: 3.3.1
- Laravel Version: 8.5.9
- PHP Version: 7.4

### Description:
Can't add use `enableHipchatNotifications` method and no methods/properties for other webhooks like Discord and Teams.
When using the HipChat method there is a `The resource you are looking for could not be found.` response.

### Steps To Reproduce:
```php
(new Forge('apiKey'))->enableHipchatNotifications('serverId', 'siteId', ["webhook_url": "webhook.com"])
```

I might be setting the data incorrectly but there is also no explination on usage.

**Comment by jbrooksuk** [comment]
The HipChat service is no longer running. These methods will be removed in the next version of the package, with other notifications added in its place.

**Comment by driesvints** [comment]
I'll keep this issue to remind us to remove them. I'll send in a PR to master when I get around for it.
