### ISSUE TITLE
Support for new feature commands 

### ISSUE THREAD

**Issue by edwinencomienda** [laravel/forge-sdk#113]
![image](https://user-images.githubusercontent.com/26597108/114794022-3399da00-9dbe-11eb-96c7-c8c683930338.png)

**Comment by driesvints** [comment]
We'll add these when we find the time.

**Comment by edwinencomienda** [comment]
is this available in the api endpoints @driesvints ?

**Comment by driesvints** [comment]
Ping @jbrooksuk

**Comment by tfevens** [comment]
Based on the reply to my tweet after release, it's not yet available in the API, but is planned to be added at some point.
https://twitter.com/jbrooksuk/status/1376910494754299908

**Comment by jbrooksuk** [comment]
We don't have any API endpoints at the moment, but it's on our list 👍 

We've recently implemented several features with no API endpoints as we're wanting to ensure the feature works as expected first.

**Comment by edwinencomienda** [comment]
that make sense @jbrooksuk  thanks!
