### ISSUE TITLE
Clear site aliases

### ISSUE THREAD

**Issue by darkons** [laravel/forge-sdk#122]
- Forge SDK Version: 3.8.0
- Laravel Version: 8.47.0
- PHP Version: 8.0
- Database Driver & Version: MySQL 8.0

### Description:
When a site has only one alias and update that site with empty aliases array that last alias is not removed.

### Steps To Reproduce:

- Create a site.
- Add one alias.
- Update site with empty aliases array.

**Comment by tfevens** [comment]
**NOTE**: This looks like an issue with the API itself, not the SDK.  Can replicate the behavior using straight API calls.

Seems that the ability to add/remove aliases from the API is not working.

I can send the following payload:
```
{
	"aliases" : []
}
```
which results in a 200 response, but the old aliases are still present:
```
{
  "site": {
    "id": 1402987,
    "server_id": 329730,
    "name": "test1.com",
    "aliases": [
      "test2.com",
      "test3.com"
    ],
    [...]
  }
}
```

**Comment by tfevens** [comment]
I went back and re-read the documentation, and my original understanding of it was incorrect.

Currently, the API only supports ADDING aliases, not DELETING.  Per the documentation:
`Use this endpoint to add additional site aliases...` 

Submitting an empty array of aliases will have no effect, as you're just telling forge "Add nothing to the aliases."

As it stands, this is working as intended.  Perhaps we can use this Issue to add the implementation to delete aliases?

**Comment by driesvints** [comment]
Feel free to send in a pr, thanks.

**Comment by tfevens** [comment]
> Feel free to send in a pr, thanks.

We can't send in a PR for a function of the API.  It's the API that's not removing the aliases, not just the SDK.

**Comment by thetispro** [comment]
You can delete aliases using Update Site: $forge->updateSite($serverId, $siteId, array $data);

See https://forge.laravel.com/api-documentation#update-site

hth
