### ISSUE TITLE
API Request works perfect from Localhost, but not from Forge

### ISSUE THREAD

**Issue by David-Grass-Feria** [laravel/forge-sdk#124]
- Forge SDK Version: 3.8.0
- Laravel Version: 8.53.0
- PHP Version: 8.0
- Database Driver & Version:mysql

I send a api request from localhost to forge. It works create, your package create the site, ssl, gitrepo..All works!!
But this works only on localhost. If i make this from a real site on forge, i get only 1 error:
"502 Bad Gateway Nginx". This error is not a part from the api documentation. I dont know, why it works from localhost, but not from forge :(

Thanks for help :)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
