### ISSUE TITLE
Specify collation on database creation

### ISSUE THREAD

**Issue by ghena** [laravel/forge-sdk#139]
Hi,
in docs I can't found a way to create a database using api with specific collation.
There is a way to do this  ?
if not maybe can be improved.
regards.

**Comment by jbrooksuk** [comment]
@ghena it's not currently possible to specify the collation of a database in Forge. Everything is created as `utf8_unicode_ci`.

**Comment by driesvints** [comment]
We'll add this to our internal backlog to maybe pick up at some point. Thanks!
