### ISSUE TITLE
Expose API endpoints for managing PHP versions

### ISSUE THREAD

**Issue by crishoj** [laravel/forge-sdk#141]
The following API endpoints seem to require a valid CSRF token:
- `PUT /servers/{id}/php/cli`
- `PUT /servers/{id}/php/default`
- `DELETE /servers/{id}/php`

Could they be made available for programmatic use, i.e. without CSRF tokens?

**Comment by jbrooksuk** [comment]
These are internal Forge endpoints, not public to the API. We can look at adding additional API endpoints for this though.

**Comment by driesvints** [comment]
Thanks @jbrooksuk

**Comment by crishoj** [comment]
> We can look at adding additional API endpoints for this though.

That would be useful!
