### ISSUE TITLE
retry method in MakesHttpRequests is sending boolean values to TimeoutException 

### ISSUE THREAD

**Issue by nsinisterra** [laravel/forge-sdk#142]
- Forge SDK Version: 3.13.0
- Laravel Version: 7.30.6
- PHP Version: 7.3.33
- Database Driver & Version: MySQL 5.7

### Description:
When retry method is used (Like in [installCertificate](https://github.com/laravel/forge-sdk/blob/master/src/Actions/ManagesCertificates.php#L109), [activateCertificate](https://github.com/laravel/forge-sdk/blob/master/src/Actions/ManagesCertificates.php#L131), etc) callback sent a boolean as result

This boolean is being sent to `TimeoutException` constructor ([MakesHttpRequests->retry method](https://github.com/laravel/forge-sdk/blob/3.x/src/MakesHttpRequests.php#L144)) which causes a fatal error, becasue [TimeoutException](https://github.com/laravel/forge-sdk/blob/master/src/Exceptions/TimeoutException.php#L22) expects null or array values, not booleans.

This was reported and handled partially in https://github.com/laravel/forge-sdk/issues/109, but not fixed for all the cases.

### Steps To Reproduce:

Just replace any retry callback to return false and wait the timeout :)

**Comment by timacdonald** [comment]
I've created a PR to address this issue: https://github.com/laravel/forge-sdk/pull/143
