### ISSUE TITLE
Call to a member function request() on null

### ISSUE THREAD

**Issue by alexandre-tobia** [laravel/forge-sdk#145]
- Forge SDK Version: #.#.#
- Laravel Version: 9.21.3
- PHP Version: 8.1.5
- Database Driver & Version: Server version: 10.5.9-MariaDB Homebrew

### Description:
When trying to find a server (or anything else) i've this error (on my local):

![Capture d’écran 2022-07-21 à 12 36 03](https://user-images.githubusercontent.com/5537783/180194179-01e4111f-c9f5-4b7e-9b34-aa40f66730c4.jpg)

### Steps To Reproduce:
Don't know, i can't reproduce it in production.

Do you have any idea to solve this ?

Thanks for your help !

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
