### ISSUE TITLE
Undefined array key "provision_command"

### ISSUE THREAD

**Issue by richardhedges** [laravel/forge-sdk#147]
- Forge SDK Version: 3.13
- Laravel Version: 9.19
- PHP Version: 8.1.9

### Description:
PHP Warning:  Undefined array key "provision_command" in /Users/richardhedges/Sites/hubv2/vendor/laravel/forge-sdk/src/Actions/ManagesServers.php on line 49

### Steps To Reproduce:
Run the `createServer` method, as in the example in the docs.

**Comment by jbrooksuk** [comment]
@richardhedges can you please provide the code you were using to provision a server with? The `provision_command` key is only available for custom servers.

**Comment by driesvints** [comment]
Feel free to respond with the above info and we'll reopen
