### ISSUE TITLE
Deployment output call returns the same log for every deployment on a server/site

### ISSUE THREAD

**Issue by marcLeeroy** [laravel/forge-sdk#152]
- Forge SDK Version: 3.13.3
- Laravel Version: does not apply
- PHP Version: 8.2
- Database Driver & Version: does not apply

### Description:

When requesting the log for a deployment (giving server id, site id and deployment id). I always get the same deployment log.

I see that you are calling the right api endpoint for this, but i guess it might be more of an issue with Forge itself. The Forge UI works great but the same info using the API is wrong, all the time.

### Steps To Reproduce:

Request 2 different logs of 2 different deployments.

**Comment by jbrooksuk** [comment]
@marcLeeroy thanks for reporting this. I've identified the bug in Forge and have deployed a fix for this.
