### ISSUE TITLE
Server ubuntuVersion property does not return a version below 20.04

### ISSUE THREAD

**Issue by iv-alec** [laravel/forge-sdk#155]
- Forge SDK Version: 3.13.3
- Laravel Version: 10.3.3
- PHP Version: 8.2
- Database Driver & Version: N/A

### Description:
Retrieving the Ubuntu version from the server using the undeclared ubuntuVersion property does not return a version below 20.04. We have many servers and are developing a tool to tell us which ones are EOL to streamline the migration process.

This may have more to do with the Forge platform itself than the SDK, but I believe if this could be fixed in Forge's core it could make a great addition to the Forge SDK.

**Comment by jbrooksuk** [comment]
Unfortunately, we do not have this information available for older servers. This property was added to Forge when we introduced support for provisioning both Ubuntu 20.04 **and** 22.04 servers.
