### ISSUE TITLE
Some functions use a hard coded timeout of 30

### ISSUE THREAD

**Issue by lhelwingkh** [laravel/forge-sdk#156]
### Forge SDK Version

3.13.3

### Laravel Version

9.52.4

### PHP Version

8.1.17

### Description

Activating a new certificate on a Forge server could take longer than the default timeout of 30 seconds which leads to a timeout error. To avoid this i have increased the timeout by using the Forge::setTimeout() function. However, when calling the ManagesCertificates::activateCertificate() function the timeout still occurs after 30 seconds. Looking into its code shows, that a timeout of 30 is passed to the retry() function as hard coded value. This applies to ManagesCertificates::installCertificate(), ManagesDaemons::restartDaemon() and ManagesWorkers::restartWorker() as well. All other calls to retry() use $this->getTimeout() to determine the timeout which is the expected bahaviour.

### Steps To Reproduce

1. Create a new certificate with obtainLetsEncryptCertificate()
2. Increase timeout to e.g. 2 minutes using setTimeout(300)
3. Activate the new certificate with activateCertificate() 
4. Wait for timeout error after 30 seconds

**Comment by lhelwingkh** [comment]
Fix proposed in https://github.com/laravel/forge-sdk/pull/157

**Comment by timacdonald** [comment]
Will close this and we can see how the PR goes.
