### ISSUE TITLE
Add $phpVersion property to Laravel\Forge\Resources\Site

### ISSUE THREAD

**Issue by sebastiansulinski** [laravel/forge-sdk#161]
Any particular reason why `phpVersion` isn't available on the `Laravel\Forge\Resources\Site` instance despite being available with the response? Could we have it added please?

**Comment by nunomaduro** [comment]
Fixed: https://github.com/laravel/forge-sdk/pull/162.

**Comment by sebastiansulinski** [comment]
Thanks @nunomaduro
