### ISSUE TITLE
Update site tags via SDK/API

### ISSUE THREAD

**Issue by benjamindulau** [laravel/forge-sdk#163]
I'm currently implementing a user specific CLI on top of Forge SDK, but I need to be able to update tags on the sites ressources.
It seems that updating tags is not possible ATM with the API, or is it?

Thanks !

**Comment by jbrooksuk** [comment]
It's possible to update a site's tags using the API. You need can pass an array of tags to https://forge.laravel.com/api-documentation#update-site
