### ISSUE TITLE
Routing in Forge Docs

### ISSUE THREAD

**Issue by ijpatricio** [laravel/forge-sdk#164]
### Description

First, I'm sorry for opening the issue in this repo. The Docs repo doesn't have "Issues" enabled, so I figured this was the best suitable option.

The issue I found is: navigation is broken, from the nav-menu, when opening in a new tab.

From my hunch, this is a Vitepress build on a public folder `/docs/**` in the forge site, or something similar, right?
It works on the navigation because of client-side routing. 
When the render comes from the server side, it doesn't find the route or the site.

From inspecting the response from `https://forge.laravel.com/docs`, I can see it serves as a redirect to `https://forge.laravel.com/docs/introduction.html`

I've done this in the past with SPA's: having one with client-side routing beneath a folder.
```
Route::get('/docs/{path?}', SpaController::class)->where('path', '.*');
```
This would serve the contents of the index view, and client side routing would do its thing.

Let me know if you would like me to find a solution with Vitepress underneath a folder.

Thanks for Laravel

### Steps To Reproduce

Go from the docs root path: https://forge.laravel.com/docs and then navigate on the left nav-menu, all is good.
After navigating, you get the `.html` "extension" on the URL, which allows you to copy-paste the link.

But, on the navigation menu, if you "open in new tab" (cmd+click), it will not contain ".html", hence the URL won't work.

Try it: https://forge.laravel.com/docs/resources/scheduler

![image](https://github.com/laravel/forge-sdk/assets/26031459/a05d34d7-5e9d-4f80-ad65-c598bdac703a)

**Comment by jbrooksuk** [comment]
Thanks for reporting this. I've deployed a change to the docs that will make the sidebar generate with the `.html` extension.
