### ISSUE TITLE
Forge link broken in docs

### ISSUE THREAD

**Issue by jdion84** [laravel/forge-sdk#165]
### Forge SDK Version

1

### Laravel Version

10

### PHP Version

8

### Description

I was not sure where to post this, but there is a link in the top-right corner of the force docs that goes to a broken URL:

Go to the docs e.g. https://forge.laravel.com/docs/resources/daemons.html

click on "Laravel Forge" in the top-right corner and it goes to https://laravel.com/forge.html

I believe it should actually go to https://forge.laravel.com

Sorry if this is the wrong place for this, I just wanted to let you know.

### Steps To Reproduce

see description

**Comment by jdion84** [comment]
"Video Tutorials" link is also broken.

**Comment by jbrooksuk** [comment]
This is deploying now.
