### ISSUE TITLE
Support `auto_source` in Site::updateDeploymentScript()

### ISSUE THREAD

**Issue by AntonCooper** [laravel/forge-sdk#166]
I need to programatically make .env variables available to deploy script. There's a way to do this in the Forge UI, but it seems that it's not supported in the SDK's `updateDeploymentScript` method. 

`$site->updateDeploymentScript($script);` only supports passing the script file and will not accept any parameter for `auto_source` 

My current work-around is to call put directly with the payload:
```php
$this->forgeApi()->put("servers/$site->serverId/sites/{$site->id}/deployment/script", [
   'content' => file_get_contents($deployScript),
   'auto_source' => true,
]);
```

**Comment by driesvints** [comment]
Will be in tomorrow's release. Thanks
