### ISSUE TITLE
Add auto-source support for `updateSiteDeploymentScript` Method

### ISSUE THREAD

**Issue by mehrancodes** [laravel/forge-sdk#169]
In order to enhance the deployment process and provide more flexibility, we need to add the ability to make `.env` variables available to the deployment script in the `forge-sdk`. This can be achieved by adding a fourth boolean argument to the `updateSiteDeploymentScript` method.

**Current Behavior**:
Currently, the method signature is:
```php
$service->forge->updateSiteDeploymentScript($serverId, $siteId, $content);
```

**Desired Behavior**:
The proposed method signature is:
```php
$service->forge->updateSiteDeploymentScript($serverId, $siteId, $content, $autoSource);
```
Where `$autoSource` is a boolean indicating whether to automatically source the `.env` variables.

**Comment by jbrooksuk** [comment]
This was done in https://github.com/laravel/forge-sdk/pull/167 and is available in https://github.com/laravel/forge-sdk/releases/tag/v3.14.0
