### ISSUE TITLE
Improve Exception handling for 422 / existing items

### ISSUE THREAD

**Issue by cord** [laravel/forge-sdk#170]
requests like
```php
$forge→createDatabase('123', [
'name' => 'test'
'user' => 'dojziam11j',
'password' => 'hQUHWg3ovi'
]);

```

can trigger a misleading Exception

```
Laravel\Forge\Exceptions\ValidationException
The given data failed to pass validation.
```

Testing in postman reveals the true reason:

![CleanShot 2023-10-30 at 12 38 53](https://github.com/laravel/forge-sdk/assets/158588/6d2e9352-2a92-4332-a513-080b299d7882)

I would expect to receive a meaningful exception with more information about the cause.

**Comment by driesvints** [comment]
We’d welcome a pr to make this more clearer

**Comment by cord** [comment]
Is this the official API package of the commercial forge business?

**Comment by jbrooksuk** [comment]
@cord this is the official package, yes.

**Comment by cord** [comment]
Great, would be nice if you can improve the customer experience with the API package by returning a meaningful exception in case of already existing items.

**Comment by jbrooksuk** [comment]
@cord, you can do the following:

```php
use Laravel\Forge\Exceptions\ValidationException;

try {
  $forge→createDatabase('123', [
    'name' => 'test'
    'user' => 'dojziam11j',
    'password' => 'hQUHWg3ovi'
  ]);
} catch (ValidationException $e) {
  dump($e->errors());
}
```

**Comment by cord** [comment]
@jbrooksuk thanks, that returns some information.

However I would expect different types of exception based on situation. Probably requires some work on forge as well.

**Comment by jbrooksuk** [comment]
@cord what kind of exceptions are you expecting? The error is a validation error, so a `ValidationException` makes sense to me.

**Comment by cord** [comment]
@jbrooksuk it seems `ValidationException` is used to cover any 422 situation, regardless of the reason. If the code should react on the different situations (e.g. 'name already taken' ,  'invalid name') we would need to compare the returned strings. 

When trying to create a server with a taken name a `FailedActionException` is thrown, so different approach here.

So I wish there would be different exceptions for each situation we need to handle.
