### ISSUE TITLE
Feature Request - Add Support for Enabling Inertia.js SSR via Forge API and SDK

### ISSUE THREAD

**Issue by mehrancodes** [laravel/forge-sdk#176]
Requesting support for enabling Inertia.js Server-Side Rendering (SSR) through Laravel Forge's API and SDK.

### Update
On my cli app [Laravel Harbor](https://github.com/mehrancodes/laravel-harbor), I added a Daemon and updated the deployment script via Forge API, but removing it is a little tricky since I don't have the Daemon ID when running it on Github workflow.

**Comment by driesvints** [comment]
Hi @mehrancodes. Unfortunately we have no plans for this right now. Thanks for your suggestion and we might pick this up in a future update.
