### ISSUE TITLE
Ability to update "Deployment Failure Emails" via SDK

### ISSUE THREAD

**Issue by aaronbushnell** [laravel/forge-sdk#178]
It would be really handy if the SDK could change the value of the "Deployment Failure Emails" for a given site. Something like:
```php
$site->deployEmails('email1@laravel.com, email2@laravel.com', $wait = true);
```

**Comment by jbrooksuk** [comment]
It's not currently possible to set notification emails via the API. However, it's in our backlog to add that and to update the SDK when available.

**Comment by euperia** [comment]
+1 from me.  I've got around 100 sites to update.

**Comment by CodyPChristian** [comment]
Yay, glad to see this as I reported it via email in the past. Just checked and it looks like its been added https://forge.laravel.com/api-documentation#set-deployment-failure-email, any ETA when it will be in this repo? @jbrooksuk @driesvints Edit: I submitted a PR for it :)

**Comment by jbrooksuk** [comment]
This was released in https://github.com/laravel/forge-sdk/releases/tag/v3.22.0
