### ISSUE TITLE
Create helpers to hold available options.

### ISSUE THREAD

**Issue by VictorAvelar** [laravel/forge-sdk#46]
It is just a personal idea (and preference) to hold all the relevant options inside classes, this gives, at least for me somehow a consistency layer on the right way of passing options as strings to the API.

Given the example on a request for creating a server:

I will like to add classes under the namespace `Themsaid\Forge\Helpers` to hold constants of valid options to pass to the API, as follows:

```php
<?php

namespace Themsaid\Forge\Helpers;

class ProvisionableServers
{
    const VULTR = 'vultr'

    const DIGITAL_OCEAN = 'ocean2'
}
```
That way when the users are creating a request, they can Reference the helper class instead of typing the option by themselves and having the risk of making a mistake. Also this turns options into a versionable element that can reflect adittions and changes to the API signature in the future.

```php
<?php

// Import autoload and so on ...

$server = $forge->createServer([
    "provider"=> ProvisionableServers::DIGITAL_OCEAN,
    "credential_id"=> 1,
    "name"=> "test-via-api",
    "size"=> ServerSize::512MB,
    "database"=> "test123",
    "php_version"=> InstallableServices::PHP_71,
    "region"=> AvailableRegions::DIGITAL_OCEAN_AMS2,
]);
```

I will be able to crate a PR and also modify the sdk docs if you think this is something you will like to have it here 😄

**Comment by driesvints** [comment]
Yes that seems a good idea. I think these can live in the root namespace, not helpers. Feel free to PR.

**Comment by VictorAvelar** [comment]
PR comming anytime soon 😄, thanks for replying.
