### ISSUE TITLE
Start and stop commands 

### ISSUE THREAD

**Issue by barryvdh** [laravel/forge-sdk#49]
Is it possible to stop a server without rebooting? And starting it later using a different call? Eg. for scaling extra servers using an API?

**Comment by themsaid** [comment]
@barryvdh can you explain more?

**Comment by barryvdh** [comment]
There is only action now: `reboot`. But you can't `shutdown` and `boot` droplets/servers, right?
For example in AWS, you don't pay for an instance that is shut down, so could be preferred to shut something down when it's not needed, and boot it when extra capacity is preferred.

**Comment by barryvdh** [comment]
So basically:

https://developers.linode.com/api/v4#operation/bootLinodeInstance
https://developers.linode.com/api/v4#operation/shutdownLinodeInstance

https://developers.digitalocean.com/documentation/v2/#power-on-a-droplet
https://developers.digitalocean.com/documentation/v2/#shutdown-a-droplet

https://docs.aws.amazon.com/cli/latest/reference/ec2/start-instances.html
https://docs.aws.amazon.com/cli/latest/reference/ec2/stop-instances.html

**Comment by tim-peterson** [comment]
@barryvdh thanks. So is this the workflow?

1. Stop server using AWS, Linode, or DigOcean API.
2. Start server using AWS, Linode, or DigOcean API.
3. Reboot server using Forge API

How does Forge know the new IP address if the stopping and starting changes it?

**Comment by barryvdh** [comment]
For load-balanced servers, you only need the internal IP, right? And workers also don't need public IPs

**Comment by tim-peterson** [comment]
Regardless the changed IP is metadata Forge needs, right? 

Did you solve this problem for yourself? If so, would you mind sharing pseudo-code to help explain what works?

**Comment by barryvdh** [comment]
Not yet, sorry. I think for scaling workload in workers/queue, I'm going for the Serverless route (waiting for Laracon for that ;) )

For webservers I'm not sure yet. I think it  it would be something like this:
 - Start (pre-configured) server
 - Trigger deployment to server to match current state of other servers
 - Health check
 - Enable load balancing to that server with Forge API
Scaling down would just be disabling load balancing to that server and stopping it.

But it would be probably not really flexible and if it's a big load then containers/kubernetes etc would be much better. 

(Also, you could assign an elastic IP to that instance I think)

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
