### ISSUE TITLE
CacheRemember Issue

### ISSUE THREAD

**Issue by AhsanAbrar** [laravel/forge-sdk#71]
Hi,

i want to store data in cache to avoid hit everytime to the server API

```php
    public function index(Forge $forge)
    {
        $servers = Cache::rememberForever('servers', function () use ($forge) {
            return $forge->servers();
        });
    }
```

I'm getting this error

> Exception: Serialization of 'Closure' is not allowed

any solution you have?

regards

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
