### ISSUE TITLE
PHP Reboot

### ISSUE THREAD

**Issue by ashpuk** [laravel/forge-sdk#74]
Hi,

it seems that forge have updated their API with regards to restarting PHP. You now need to include the Version of PHP that you want to restart (as forge servers can now handle multiple versions of PHP on the same server).

If you do not provide the PHP version then you get a validation error when trying the API request.

Can you please update the SDK so that it supports this.

Thanks :)

**Comment by jbrooksuk** [comment]
Thanks, this is now on `master`.
